In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df = pd.read_csv("/content/UHI_Effect_India.csv")

In [25]:
df.head()

City  Temperature_C  Population_Density  Green_Cover_%  \
0    Chennai          20.47               19385          23.82   
1       Pune          33.13               12181          32.33   
2  Bangalore          29.81               18445          16.01   
3       Pune          26.84               17875          21.87   
4       Pune          28.81                8414          38.90   

  Industrial_Activity_Level  Vehicular_Emissions_Index  Humidity_%  \
0                       Low                     284.41       48.83   
1                    Medium                     278.59       80.16   
2                    Medium                     113.44       53.66   
3                    Medium                     150.45       81.02   
4                       Low                     210.83       70.58   

   Land_Surface_Temperature_C  Nighttime_Temperature_C UHI_Effect_Severity  
0                       26.79                    16.72                 Low  
1                       37.63                    31.52              Medium  
2                       35.89                    28.38                 Low  
3                       32.61                    23.97                 Low  
4                       31.79                    26.25                 Low

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   City                        5000 non-null   object 
 1   Temperature_C               5000 non-null   float64
 2   Population_Density          5000 non-null   int64  
 3   Green_Cover_%               5000 non-null   float64
 4   Industrial_Activity_Level   5000 non-null   object 
 5   Vehicular_Emissions_Index   5000 non-null   float64
 6   Humidity_%                  5000 non-null   float64
 7   Land_Surface_Temperature_C  5000 non-null   float64
 8   Nighttime_Temperature_C     5000 non-null   float64
 9   UHI_Effect_Severity         5000 non-null   object 
dtypes: float64(6), int64(1), object(3)
memory usage: 390.8+ KB


In [27]:
df.describe()

Temperature_C  Population_Density  Green_Cover_%  \
count    5000.000000         5000.000000    5000.000000   
mean       34.873936        17704.587400      22.663184   
std         5.099969         7222.622776      10.077169   
min        16.560000         5005.000000       5.010000   
25%        31.400000        11442.500000      13.920000   
50%        34.860000        17807.000000      22.805000   
75%        38.382500        24011.000000      31.422500   
max        52.650000        29996.000000      40.000000   

       Vehicular_Emissions_Index   Humidity_%  Land_Surface_Temperature_C  \
count                5000.000000  5000.000000                 5000.000000   
mean                  173.169060    64.969614                   39.855240   
std                    71.320703    14.413531                    5.389853   
min                    50.030000    40.000000                   19.900000   
25%                   111.717500    52.340000                   36.187500   
50%                   172.795000    65.075000                   39.835000   
75%                   232.697500    77.440000                   43.570000   
max                   299.920000    89.990000                   59.340000   

       Nighttime_Temperature_C  
count              5000.000000  
mean                 32.372018  
std                   5.149341  
min                  13.120000  
25%                  28.940000  
50%                  32.350000  
75%                  35.882500  
max                  49.940000

In [28]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
categorical_columns = ['City', 'Industrial_Activity_Level', 'UHI_Effect_Severity']

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

In [29]:
df.head()

City  Temperature_C  Population_Density  Green_Cover_%  \
0     1          20.47               19385          23.82   
1     4          33.13               12181          32.33   
2     0          29.81               18445          16.01   
3     4          26.84               17875          21.87   
4     4          28.81                8414          38.90   

   Industrial_Activity_Level  Vehicular_Emissions_Index  Humidity_%  \
0                          1                     284.41       48.83   
1                          2                     278.59       80.16   
2                          2                     113.44       53.66   
3                          2                     150.45       81.02   
4                          1                     210.83       70.58   

   Land_Surface_Temperature_C  Nighttime_Temperature_C  UHI_Effect_Severity  
0                       26.79                    16.72                    1  
1                       37.63                    31.52                    2  
2                       35.89                    28.38                    1  
3                       32.61                    23.97                    1  
4                       31.79                    26.25                    1

In [32]:
# Step 3: seperate x and y variable

x = df.drop(columns=["UHI_Effect_Severity"])  # Features
y = df["UHI_Effect_Severity"]  # Target variable

In [33]:
# Step 4: Split data into training and testing sets (80% train, 20% test)
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [34]:
# Step 5: standardize the data to improve model performance
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [35]:
# Step 6: Train the Logistic Regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)



LogisticRegression()

In [36]:
# Step 7: Make predictions
ypred = model.predict(xtest)

In [37]:
# Step 8: Evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
conf_matrix = confusion_matrix(ytest, ypred)
class_report = classification_report(ytest, ypred)

# Print results
print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Model Accuracy: 0.973
Confusion Matrix:
 [[266   0   7]
 [  0 361   6]
 [  5   9 346]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.97      0.98       273
           1       0.98      0.98      0.98       367
           2       0.96      0.96      0.96       360

    accuracy                           0.97      1000
   macro avg       0.97      0.97      0.97      1000
weighted avg       0.97      0.97      0.97      1000

